name: CI

on:
  pull_request:
    branches:
      - development

jobs:
  lint:
    runs-on: ubuntu-20.04
    container:
      image: artifacthub/ah
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ah lint
        working-directory: ./charts/mlrun-ce
        run: ah lint
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Extract private key
      run: echo "${{ secrets.MLRUN_PEM }}" > mlrun.pem
    - name: Set permissions on key
      run: chmod 400 mlrun.pem
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
    - name: Copy folder to remote machine
      run: sudo scp -r -o StrictHostKeyChecking=no -i mlrun.pem  /home/runner/work/ce ${{ secrets.USERNAME }}@${{ secrets.IP }}
    - name: Run commands on remote machine
      run: |
        sshpass ssh -o StrictHostKeyChecking=no -i  mlrun.pem ${{ secrets.USERNAME }}@${{ secrets.IP }} <<EOF
        ls;
        pwd;
        echo Deleting mlrun namepsace;
        kubectl delete namespace mlrun 2>/dev/null;
        echo Creating mlrun helm from copied folder using make;
        cd ce;
        make;
        echo Reinstalling Community Edition;
        helm install mlrun-ce --namespace ${NAMESPACE} \
        --set minio.resources.requests.memory="128Mi" \
        --set  jupyterNotebook.persistence.size="1Gi" \
        --set  mlrun.db.persistence.size="1Gi" \
        --set  mlrun.api.persistence.size="1Gi" \
        --set  mpi-operator.deployment.create="false" \
        --set  mlrun.httpDB.dbType="sqlite" \
        --set  mlrun.httpDB.dirPath="/mlrun/db" \
        --set  mlrun.httpDB.dsn="sqlite:////mlrun/db/mlrun.db?check_same_thread=false"  \
        --set  mlrun.httpDB.oldDsn=""  \
        --set global.registry.url=$(minikube ip):5000  --set global.registry.secretName=""   \
        --set global.externalHostAddress=$(minikube ip)  \
        --set nuclio.dashboard.externalIPAddresses[0]=$(minikube ip)  \
        --wait --debug --timeout=1h mlrun/mlrun-ce --version 0.6.0-rc1
        EOF
        rm -rf mlrun.pem
        
  
  # commented out for now, takes too long to pull images
  # perhaps we can invoke it via workflow dispatch or as a nightly job
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Kubernetes cluster
  #       uses: helm/kind-action@v1.4.0
  #       with:
  #         config: ./.github/assets/kind.yaml
  #         wait: 180s
  #         kubectl_version: v1.23.13
  #         node_image: kindest/node:v1.23.13
  #     - name: Setup Helm
  #       uses: azure/setup-helm@v3
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Run tests
  #       run : make tests
